###################################################################

# Created by write_sdc on Thu Oct 17 15:53:14 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions TT0P9V25C -library um28nchslogl30hdh140f_tt0p9v25c
set_max_fanout 16 [current_design]
set_wire_load_selection_group um28nchslogl30hdh140f -library                   \
um28nchslogl30hdh140f_tt0p9v25c
set_load -pin_load 0.01 [get_ports skip_out]
set_load -pin_load 0.01 [get_ports {G_out[15]}]
set_load -pin_load 0.01 [get_ports {G_out[14]}]
set_load -pin_load 0.01 [get_ports {G_out[13]}]
set_load -pin_load 0.01 [get_ports {G_out[12]}]
set_load -pin_load 0.01 [get_ports {G_out[11]}]
set_load -pin_load 0.01 [get_ports {G_out[10]}]
set_load -pin_load 0.01 [get_ports {G_out[9]}]
set_load -pin_load 0.01 [get_ports {G_out[8]}]
set_load -pin_load 0.01 [get_ports {G_out[7]}]
set_load -pin_load 0.01 [get_ports {G_out[6]}]
set_load -pin_load 0.01 [get_ports {G_out[5]}]
set_load -pin_load 0.01 [get_ports {G_out[4]}]
set_load -pin_load 0.01 [get_ports {G_out[3]}]
set_load -pin_load 0.01 [get_ports {G_out[2]}]
set_load -pin_load 0.01 [get_ports {G_out[1]}]
set_load -pin_load 0.01 [get_ports {G_out[0]}]
set_load -pin_load 0.01 [get_ports {d_out[31]}]
set_load -pin_load 0.01 [get_ports {d_out[30]}]
set_load -pin_load 0.01 [get_ports {d_out[29]}]
set_load -pin_load 0.01 [get_ports {d_out[28]}]
set_load -pin_load 0.01 [get_ports {d_out[27]}]
set_load -pin_load 0.01 [get_ports {d_out[26]}]
set_load -pin_load 0.01 [get_ports {d_out[25]}]
set_load -pin_load 0.01 [get_ports {d_out[24]}]
set_load -pin_load 0.01 [get_ports {d_out[23]}]
set_load -pin_load 0.01 [get_ports {d_out[22]}]
set_load -pin_load 0.01 [get_ports {d_out[21]}]
set_load -pin_load 0.01 [get_ports {d_out[20]}]
set_load -pin_load 0.01 [get_ports {d_out[19]}]
set_load -pin_load 0.01 [get_ports {d_out[18]}]
set_load -pin_load 0.01 [get_ports {d_out[17]}]
set_load -pin_load 0.01 [get_ports {d_out[16]}]
set_load -pin_load 0.01 [get_ports {d_out[15]}]
set_load -pin_load 0.01 [get_ports {d_out[14]}]
set_load -pin_load 0.01 [get_ports {d_out[13]}]
set_load -pin_load 0.01 [get_ports {d_out[12]}]
set_load -pin_load 0.01 [get_ports {d_out[11]}]
set_load -pin_load 0.01 [get_ports {d_out[10]}]
set_load -pin_load 0.01 [get_ports {d_out[9]}]
set_load -pin_load 0.01 [get_ports {d_out[8]}]
set_load -pin_load 0.01 [get_ports {d_out[7]}]
set_load -pin_load 0.01 [get_ports {d_out[6]}]
set_load -pin_load 0.01 [get_ports {d_out[5]}]
set_load -pin_load 0.01 [get_ports {d_out[4]}]
set_load -pin_load 0.01 [get_ports {d_out[3]}]
set_load -pin_load 0.01 [get_ports {d_out[2]}]
set_load -pin_load 0.01 [get_ports {d_out[1]}]
set_load -pin_load 0.01 [get_ports {d_out[0]}]
set_load -pin_load 0.01 [get_ports {alpha_out[15]}]
set_load -pin_load 0.01 [get_ports {alpha_out[14]}]
set_load -pin_load 0.01 [get_ports {alpha_out[13]}]
set_load -pin_load 0.01 [get_ports {alpha_out[12]}]
set_load -pin_load 0.01 [get_ports {alpha_out[11]}]
set_load -pin_load 0.01 [get_ports {alpha_out[10]}]
set_load -pin_load 0.01 [get_ports {alpha_out[9]}]
set_load -pin_load 0.01 [get_ports {alpha_out[8]}]
set_load -pin_load 0.01 [get_ports {alpha_out[7]}]
set_load -pin_load 0.01 [get_ports {alpha_out[6]}]
set_load -pin_load 0.01 [get_ports {alpha_out[5]}]
set_load -pin_load 0.01 [get_ports {alpha_out[4]}]
set_load -pin_load 0.01 [get_ports {alpha_out[3]}]
set_load -pin_load 0.01 [get_ports {alpha_out[2]}]
set_load -pin_load 0.01 [get_ports {alpha_out[1]}]
set_load -pin_load 0.01 [get_ports {alpha_out[0]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[63]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[62]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[61]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[60]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[59]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[58]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[57]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[56]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[55]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[54]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[53]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[52]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[51]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[50]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[49]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[48]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[47]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[46]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[45]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[44]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[43]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[42]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[41]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[40]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[39]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[38]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[37]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[36]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[35]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[34]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[33]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[32]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[31]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[30]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[29]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[28]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[27]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[26]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[25]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[24]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[23]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[22]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[21]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[20]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[19]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[18]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[17]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[16]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[15]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[14]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[13]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[12]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[11]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[10]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[9]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[8]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[7]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[6]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[5]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[4]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[3]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[2]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[1]}]
set_load -pin_load 0.01 [get_ports {conic_opacity_out[0]}]
set_load -pin_load 0.01 [get_ports skip_and_alpha_done_out]
set_load -pin_load 0.01 [get_ports early_skip]
create_clock [get_ports clk]  -period 1  -waveform {0 0.5}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  -max 0.5  [get_ports rst_n]
set_input_delay -clock clk  -min 0.1  [get_ports rst_n]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[15]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[14]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[13]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[12]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[11]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[10]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[9]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[8]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[8]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[7]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[6]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[5]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[4]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[3]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[2]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[1]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {block_id[0]}]
set_input_delay -clock clk  -min 0.1  [get_ports {block_id[0]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[31]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[30]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[29]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[28]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[27]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[26]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[25]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[24]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[24]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[23]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[22]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[21]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[20]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[19]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[18]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[17]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[16]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[16]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[15]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[14]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[13]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[12]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[11]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[10]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[9]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[8]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[8]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[7]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[6]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[5]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[4]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[3]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[2]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[1]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {mean2D[0]}]
set_input_delay -clock clk  -min 0.1  [get_ports {mean2D[0]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[63]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[63]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[62]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[62]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[61]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[61]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[60]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[60]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[59]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[59]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[58]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[58]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[57]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[57]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[56]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[56]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[55]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[55]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[54]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[54]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[53]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[53]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[52]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[52]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[51]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[51]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[50]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[50]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[49]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[49]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[48]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[48]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[47]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[47]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[46]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[46]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[45]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[45]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[44]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[44]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[43]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[43]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[42]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[42]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[41]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[41]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[40]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[40]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[39]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[39]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[38]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[38]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[37]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[37]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[36]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[36]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[35]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[35]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[34]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[34]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[33]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[33]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[32]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[32]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[31]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[30]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[29]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[28]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[27]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[26]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[25]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[24]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[24]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[23]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[22]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[21]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[20]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[19]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[18]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[17]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[16]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[16]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[15]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[14]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[13]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[12]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[11]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[10]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[9]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[8]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[8]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[7]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[6]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[5]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[4]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[3]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[2]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[1]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {conic_opacity[0]}]
set_input_delay -clock clk  -min 0.1  [get_ports {conic_opacity[0]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[7]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[6]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[5]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[4]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[3]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[2]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[1]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {pixel_id[0]}]
set_input_delay -clock clk  -min 0.1  [get_ports {pixel_id[0]}]
set_input_delay -clock clk  -max 0.5  [get_ports i_valid]
set_input_delay -clock clk  -min 0.1  [get_ports i_valid]
set_output_delay -clock clk  -max 0.5  [get_ports skip_out]
set_output_delay -clock clk  -min 0.1  [get_ports skip_out]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[15]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[15]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[14]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[14]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[13]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[13]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[12]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[12]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[11]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[11]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[10]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[10]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[9]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[9]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[8]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[8]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[7]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[7]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[6]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[6]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[5]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[5]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[4]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[4]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[3]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[3]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[2]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[2]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[1]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[1]}]
set_output_delay -clock clk  -max 0.5  [get_ports {G_out[0]}]
set_output_delay -clock clk  -min 0.1  [get_ports {G_out[0]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[31]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[31]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[30]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[30]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[29]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[29]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[28]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[28]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[27]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[27]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[26]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[26]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[25]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[25]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[24]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[24]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[23]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[23]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[22]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[22]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[21]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[21]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[20]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[20]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[19]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[19]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[18]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[18]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[17]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[17]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[16]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[16]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[15]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[15]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[14]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[14]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[13]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[13]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[12]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[12]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[11]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[11]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[10]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[10]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[9]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[9]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[8]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[8]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[7]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[7]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[6]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[6]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[5]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[5]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[4]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[4]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[3]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[3]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[2]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[2]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[1]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[1]}]
set_output_delay -clock clk  -max 0.5  [get_ports {d_out[0]}]
set_output_delay -clock clk  -min 0.1  [get_ports {d_out[0]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[15]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[15]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[14]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[14]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[13]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[13]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[12]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[12]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[11]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[11]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[10]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[10]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[9]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[9]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[8]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[8]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[7]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[7]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[6]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[6]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[5]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[5]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[4]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[4]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[3]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[3]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[2]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[2]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[1]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[1]}]
set_output_delay -clock clk  -max 0.5  [get_ports {alpha_out[0]}]
set_output_delay -clock clk  -min 0.1  [get_ports {alpha_out[0]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[63]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[63]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[62]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[62]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[61]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[61]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[60]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[60]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[59]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[59]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[58]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[58]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[57]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[57]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[56]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[56]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[55]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[55]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[54]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[54]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[53]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[53]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[52]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[52]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[51]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[51]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[50]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[50]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[49]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[49]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[48]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[48]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[47]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[47]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[46]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[46]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[45]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[45]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[44]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[44]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[43]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[43]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[42]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[42]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[41]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[41]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[40]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[40]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[39]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[39]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[38]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[38]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[37]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[37]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[36]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[36]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[35]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[35]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[34]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[34]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[33]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[33]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[32]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[32]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[31]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[31]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[30]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[30]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[29]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[29]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[28]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[28]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[27]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[27]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[26]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[26]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[25]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[25]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[24]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[24]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[23]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[23]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[22]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[22]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[21]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[21]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[20]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[20]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[19]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[19]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[18]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[18]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[17]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[17]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[16]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[16]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[15]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[15]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[14]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[14]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[13]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[13]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[12]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[12]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[11]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[11]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[10]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[10]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[9]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[9]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[8]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[8]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[7]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[7]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[6]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[6]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[5]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[5]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[4]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[4]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[3]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[3]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[2]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[2]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[1]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[1]}]
set_output_delay -clock clk  -max 0.5  [get_ports {conic_opacity_out[0]}]
set_output_delay -clock clk  -min 0.1  [get_ports {conic_opacity_out[0]}]
set_output_delay -clock clk  -max 0.5  [get_ports skip_and_alpha_done_out]
set_output_delay -clock clk  -min 0.1  [get_ports skip_and_alpha_done_out]
set_output_delay -clock clk  -max 0.5  [get_ports early_skip]
set_output_delay -clock clk  -min 0.1  [get_ports early_skip]
set_input_transition -max 0.1  [get_ports clk]
set_input_transition -min 0.1  [get_ports clk]
set_input_transition -max 0.1  [get_ports rst_n]
set_input_transition -min 0.1  [get_ports rst_n]
set_input_transition -max 0.1  [get_ports {block_id[15]}]
set_input_transition -min 0.1  [get_ports {block_id[15]}]
set_input_transition -max 0.1  [get_ports {block_id[14]}]
set_input_transition -min 0.1  [get_ports {block_id[14]}]
set_input_transition -max 0.1  [get_ports {block_id[13]}]
set_input_transition -min 0.1  [get_ports {block_id[13]}]
set_input_transition -max 0.1  [get_ports {block_id[12]}]
set_input_transition -min 0.1  [get_ports {block_id[12]}]
set_input_transition -max 0.1  [get_ports {block_id[11]}]
set_input_transition -min 0.1  [get_ports {block_id[11]}]
set_input_transition -max 0.1  [get_ports {block_id[10]}]
set_input_transition -min 0.1  [get_ports {block_id[10]}]
set_input_transition -max 0.1  [get_ports {block_id[9]}]
set_input_transition -min 0.1  [get_ports {block_id[9]}]
set_input_transition -max 0.1  [get_ports {block_id[8]}]
set_input_transition -min 0.1  [get_ports {block_id[8]}]
set_input_transition -max 0.1  [get_ports {block_id[7]}]
set_input_transition -min 0.1  [get_ports {block_id[7]}]
set_input_transition -max 0.1  [get_ports {block_id[6]}]
set_input_transition -min 0.1  [get_ports {block_id[6]}]
set_input_transition -max 0.1  [get_ports {block_id[5]}]
set_input_transition -min 0.1  [get_ports {block_id[5]}]
set_input_transition -max 0.1  [get_ports {block_id[4]}]
set_input_transition -min 0.1  [get_ports {block_id[4]}]
set_input_transition -max 0.1  [get_ports {block_id[3]}]
set_input_transition -min 0.1  [get_ports {block_id[3]}]
set_input_transition -max 0.1  [get_ports {block_id[2]}]
set_input_transition -min 0.1  [get_ports {block_id[2]}]
set_input_transition -max 0.1  [get_ports {block_id[1]}]
set_input_transition -min 0.1  [get_ports {block_id[1]}]
set_input_transition -max 0.1  [get_ports {block_id[0]}]
set_input_transition -min 0.1  [get_ports {block_id[0]}]
set_input_transition -max 0.1  [get_ports {mean2D[31]}]
set_input_transition -min 0.1  [get_ports {mean2D[31]}]
set_input_transition -max 0.1  [get_ports {mean2D[30]}]
set_input_transition -min 0.1  [get_ports {mean2D[30]}]
set_input_transition -max 0.1  [get_ports {mean2D[29]}]
set_input_transition -min 0.1  [get_ports {mean2D[29]}]
set_input_transition -max 0.1  [get_ports {mean2D[28]}]
set_input_transition -min 0.1  [get_ports {mean2D[28]}]
set_input_transition -max 0.1  [get_ports {mean2D[27]}]
set_input_transition -min 0.1  [get_ports {mean2D[27]}]
set_input_transition -max 0.1  [get_ports {mean2D[26]}]
set_input_transition -min 0.1  [get_ports {mean2D[26]}]
set_input_transition -max 0.1  [get_ports {mean2D[25]}]
set_input_transition -min 0.1  [get_ports {mean2D[25]}]
set_input_transition -max 0.1  [get_ports {mean2D[24]}]
set_input_transition -min 0.1  [get_ports {mean2D[24]}]
set_input_transition -max 0.1  [get_ports {mean2D[23]}]
set_input_transition -min 0.1  [get_ports {mean2D[23]}]
set_input_transition -max 0.1  [get_ports {mean2D[22]}]
set_input_transition -min 0.1  [get_ports {mean2D[22]}]
set_input_transition -max 0.1  [get_ports {mean2D[21]}]
set_input_transition -min 0.1  [get_ports {mean2D[21]}]
set_input_transition -max 0.1  [get_ports {mean2D[20]}]
set_input_transition -min 0.1  [get_ports {mean2D[20]}]
set_input_transition -max 0.1  [get_ports {mean2D[19]}]
set_input_transition -min 0.1  [get_ports {mean2D[19]}]
set_input_transition -max 0.1  [get_ports {mean2D[18]}]
set_input_transition -min 0.1  [get_ports {mean2D[18]}]
set_input_transition -max 0.1  [get_ports {mean2D[17]}]
set_input_transition -min 0.1  [get_ports {mean2D[17]}]
set_input_transition -max 0.1  [get_ports {mean2D[16]}]
set_input_transition -min 0.1  [get_ports {mean2D[16]}]
set_input_transition -max 0.1  [get_ports {mean2D[15]}]
set_input_transition -min 0.1  [get_ports {mean2D[15]}]
set_input_transition -max 0.1  [get_ports {mean2D[14]}]
set_input_transition -min 0.1  [get_ports {mean2D[14]}]
set_input_transition -max 0.1  [get_ports {mean2D[13]}]
set_input_transition -min 0.1  [get_ports {mean2D[13]}]
set_input_transition -max 0.1  [get_ports {mean2D[12]}]
set_input_transition -min 0.1  [get_ports {mean2D[12]}]
set_input_transition -max 0.1  [get_ports {mean2D[11]}]
set_input_transition -min 0.1  [get_ports {mean2D[11]}]
set_input_transition -max 0.1  [get_ports {mean2D[10]}]
set_input_transition -min 0.1  [get_ports {mean2D[10]}]
set_input_transition -max 0.1  [get_ports {mean2D[9]}]
set_input_transition -min 0.1  [get_ports {mean2D[9]}]
set_input_transition -max 0.1  [get_ports {mean2D[8]}]
set_input_transition -min 0.1  [get_ports {mean2D[8]}]
set_input_transition -max 0.1  [get_ports {mean2D[7]}]
set_input_transition -min 0.1  [get_ports {mean2D[7]}]
set_input_transition -max 0.1  [get_ports {mean2D[6]}]
set_input_transition -min 0.1  [get_ports {mean2D[6]}]
set_input_transition -max 0.1  [get_ports {mean2D[5]}]
set_input_transition -min 0.1  [get_ports {mean2D[5]}]
set_input_transition -max 0.1  [get_ports {mean2D[4]}]
set_input_transition -min 0.1  [get_ports {mean2D[4]}]
set_input_transition -max 0.1  [get_ports {mean2D[3]}]
set_input_transition -min 0.1  [get_ports {mean2D[3]}]
set_input_transition -max 0.1  [get_ports {mean2D[2]}]
set_input_transition -min 0.1  [get_ports {mean2D[2]}]
set_input_transition -max 0.1  [get_ports {mean2D[1]}]
set_input_transition -min 0.1  [get_ports {mean2D[1]}]
set_input_transition -max 0.1  [get_ports {mean2D[0]}]
set_input_transition -min 0.1  [get_ports {mean2D[0]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[63]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[63]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[62]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[62]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[61]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[61]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[60]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[60]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[59]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[59]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[58]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[58]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[57]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[57]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[56]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[56]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[55]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[55]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[54]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[54]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[53]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[53]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[52]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[52]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[51]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[51]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[50]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[50]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[49]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[49]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[48]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[48]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[47]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[47]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[46]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[46]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[45]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[45]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[44]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[44]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[43]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[43]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[42]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[42]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[41]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[41]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[40]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[40]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[39]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[39]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[38]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[38]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[37]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[37]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[36]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[36]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[35]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[35]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[34]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[34]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[33]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[33]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[32]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[32]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[31]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[31]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[30]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[30]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[29]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[29]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[28]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[28]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[27]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[27]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[26]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[26]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[25]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[25]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[24]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[24]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[23]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[23]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[22]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[22]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[21]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[21]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[20]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[20]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[19]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[19]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[18]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[18]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[17]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[17]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[16]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[16]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[15]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[15]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[14]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[14]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[13]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[13]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[12]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[12]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[11]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[11]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[10]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[10]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[9]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[9]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[8]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[8]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[7]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[7]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[6]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[6]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[5]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[5]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[4]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[4]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[3]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[3]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[2]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[2]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[1]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[1]}]
set_input_transition -max 0.1  [get_ports {conic_opacity[0]}]
set_input_transition -min 0.1  [get_ports {conic_opacity[0]}]
set_input_transition -max 0.1  [get_ports {pixel_id[7]}]
set_input_transition -min 0.1  [get_ports {pixel_id[7]}]
set_input_transition -max 0.1  [get_ports {pixel_id[6]}]
set_input_transition -min 0.1  [get_ports {pixel_id[6]}]
set_input_transition -max 0.1  [get_ports {pixel_id[5]}]
set_input_transition -min 0.1  [get_ports {pixel_id[5]}]
set_input_transition -max 0.1  [get_ports {pixel_id[4]}]
set_input_transition -min 0.1  [get_ports {pixel_id[4]}]
set_input_transition -max 0.1  [get_ports {pixel_id[3]}]
set_input_transition -min 0.1  [get_ports {pixel_id[3]}]
set_input_transition -max 0.1  [get_ports {pixel_id[2]}]
set_input_transition -min 0.1  [get_ports {pixel_id[2]}]
set_input_transition -max 0.1  [get_ports {pixel_id[1]}]
set_input_transition -min 0.1  [get_ports {pixel_id[1]}]
set_input_transition -max 0.1  [get_ports {pixel_id[0]}]
set_input_transition -min 0.1  [get_ports {pixel_id[0]}]
set_input_transition -max 0.1  [get_ports i_valid]
set_input_transition -min 0.1  [get_ports i_valid]
